apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: gcp-sa
          mountPath: /gcp-sa
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /gcp-sa/gcp-sa.json
        volumes:
          - name: gcp-sa
            secret:
              secretName: gke-gcp-sa
