apiVersion: v1
kind: Namespace
metadata:
  name: thomasflanigan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: thomasflanigan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: nginx
#       Meant to be run with envsubst
        image: $TOMS_SITE_IMG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-svc
  namespace: thomasflanigan
spec:
  selector:
    app: site
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: thomasflanigan
    networking.gke.io/managed-certificates: site-cert
  name: site-ingress
  namespace: thomasflanigan
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: site-svc
              servicePort: 8080
            path: /*
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: site-cert
  namespace: thomasflanigan
spec:
  domains:
    - thomasflanigan.com
